load_files: true # if true: remove and reload the result folder, else: remove and create a new one 
max_cpus: 3   # limit the number of CPUs due to high memory usage
table: 
    name: table
    num_robots: [2, 3]
    envs: [windows, forest]
    algs: [coltrans, dbcbs]
    metrics: [Error, Energy]
flights: 
  extract: true
  data:
    dbcbs: 
      2cfs_windows: 
        - [data/dbcbs/cf9_01]
        - [data/dbcbs/cf9_04]
        - [data/dbcbs/cf9_05]
        - [data/dbcbs/cf9_10]
        - [data/dbcbs/cf9_12]
        - [data/dbcbs/cf9_27]
        - [data/dbcbs/cf9_28]
        - [data/dbcbs/cf9_31]
        - [data/dbcbs/cf9_32]
        - [data/dbcbs/cf9_36]
      3cfs_window: []
      2cfs_forest: []
      3cfs_forest: []   
    coltrans:
      2cfs_windows: 
        - [data/coltransplanning/cf9_02]
        - [data/coltransplanning/cf9_03]
        - [data/coltransplanning/cf9_06]
        - [data/coltransplanning/cf9_11]
        - [data/coltransplanning/cf9_13]
        - [data/coltransplanning/cf9_14]
        - [data/coltransplanning/cf9_25]
        - [data/coltransplanning/cf9_29]
        - [data/coltransplanning/cf9_33]
        - [data/coltransplanning/cf9_34]
      3cfs_window: []
      2cfs_forest: []
      3cfs_forest: []
start_time: [1.0  , 1.0 , 1.0 , 1.0 , 1.0 , 1.0 , 1.0, 1.0, 1.0, 1.0]
end_time:   [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0,40.0, 40.0, 40.0]
plot:
  enabled: true
  files:
    dbcbs: 
      2cfs_windows: 
        - [data/dbcbs/cf9_01]
        # - [data/dbcbs/cf9_04]
        # - [data/dbcbs/cf9_05]
        # - [data/dbcbs/cf9_10]
        # - [data/dbcbs/cf9_12]
        # - [data/dbcbs/cf9_27]
        # - [data/dbcbs/cf9_28]
        # - [data/dbcbs/cf9_31]
        # - [data/dbcbs/cf9_32]
        # - [data/dbcbs/cf9_36]
      3cfs_window: []
      2cfs_forest: []
      3cfs_forest: []
    coltrans: 
      2cfs_windows: 
        - [data/coltransplanning/cf9_02]
        # - [data/coltransplanning/cf9_03]
        # - [data/coltransplanning/cf9_06]
        # - [data/coltransplanning/cf9_11]
        # - [data/coltransplanning/cf9_13]
        # - [data/coltransplanning/cf9_14]
        # - [data/coltransplanning/cf9_25]
        # - [data/coltransplanning/cf9_29]
        # - [data/coltransplanning/cf9_33]
        # - [data/coltransplanning/cf9_34]
        # - [data/coltransplanning/cf9_38]
      3cfs_window: []
      2cfs_forest: []
      3cfs_forest: []

data_to_plot:  
    page1:
      special: true # if this plot needs a special calculation 
      plot_labels: ["x [m]", "y [m]", "z [m]"]
      unit: mm 
      data:
        name1: p0
        data1: [stateEstimateZ.px, stateEstimateZ.py, stateEstimateZ.pz]
        name2: p0d
        data2: [ctrltargetZ.x, ctrltargetZ.y, ctrltargetZ.z]
        timestamp: []
      title: Payload Pose
      num_of_plots: 3
    page2:
      special: false
      plot_labels: ['vx [m/s]', 'vy [m/s]', 'vz [m/s]']
      unit: mm
      data:
        name1: v0d
        data1: [ctrltargetZ.vx, ctrltargetZ.vy, ctrltargetZ.vz]
        name2: v0
        data2: [stateEstimateZ.pvx, stateEstimateZ.pvy, stateEstimateZ.pvz]
        # name3: filtered_vel
        # data3: [stateEstimateZ.px, stateEstimateZ.py, stateEstimateZ.pz, timestamp]
      title: Payload Velocity
      num_of_plots: 3


    page3:
      special: false
      plot_labels: ['r [rad]', 'p [rad]', 'y [rad]']
      unit: rad
      data:
        name1: rpyd
        data1: [ctrlLeeP.rpydx, ctrlLeeP.rpydy, ctrlLeeP.rpydz] 
        name2: rpy
        data2: [ctrlLeeP.rpyx, ctrlLeeP.rpyy, ctrlLeeP.rpyz]
      title: rpy
      num_of_plots: 3


    page4:
      special: false
      plot_labels: ['wx [rad/s]', 'wy [rad/s]', 'wz [rad/s]']
      unit: s
      data:
        # name1: gyro
        # data1: [gyro.x, gyro.y, gyro.z]
        name1: wd
        data1: [ctrlLeeP.omegarx, ctrlLeeP.omegary, ctrlLeeP.omegarz]
        name2: w
        data2: [ctrlLeeP.omegax, ctrlLeeP.omegay, ctrlLeeP.omegaz]
      title: angular velocity
      num_of_plots: 3

    page5:
      special: false
      plot_labels: ['desmux [N]', 'desmuy [N]', 'desmuz [N]']
      unit: N
      data:
        name1: muref
        data1: [ctrlLeeP.mu_refx, ctrlLeeP.mu_refy, ctrlLeeP.mu_refz]
        name2: mudes
        data2: [ctrlLeeP.desVirtInpx, ctrlLeeP.desVirtInpy, ctrlLeeP.desVirtInpz]
      title: Desired Cable Force
      num_of_plots: 3

    page6:
      special: false
      plot_labels: ['qi []', 'qi []', 'qi []']
      unit: "[]"
      data:
        name1: qid
        data1: [ctrlLeeP.qdix, ctrlLeeP.qdiy, ctrlLeeP.qdiz]
        name2: qi
        data2: [ctrlLeeP.qix, ctrlLeeP.qiy, ctrlLeeP.qiz]
      title: Cable Vector
      num_of_plots: 3


    page7:
      special: false
      plot_labels: ['qidot [rad/s]', 'qidot [rad/s]', 'qidot [rad/s]']
      unit: rad/s
      data:
        name1: qiref
        data1: [ctrlLeeP.qidrefx, ctrlLeeP.qidrefy, ctrlLeeP.qidrefz]
        name2: qidot
        data2: [ctrlLeeP.qidotx, ctrlLeeP.qidoty, ctrlLeeP.qidotz]
      title: Cable angular velocity
      num_of_plots: 3

    page8:
      special: false
      plot_labels: ['Fdx [N]', 'Fdy [N]', 'Fdz [N]']
      unit: N
      data:
        name1: Fd
        data1: [ctrlLeeP.Fdx, ctrlLeeP.Fdy, ctrlLeeP.Fdz]
      title: Desired Payload Force
      num_of_plots: 3

    page9:
      special: false # if this plot needs a special calculation 
      plot_labels: ["x [m/s2]", "y [m/s2]", "z [m/s2]"]
      unit: m/s2
      data:
        name1: aw
        data1: [stateEstimate.ax, stateEstimate.ay, stateEstimate.az]
      title: UAV acceleration
      num_of_plots: 3
